### ISSUE TITLE
Liquibase meta-data tables falsely identified as already existing

### ISSUE THREAD

**Issue by El-Carverino** [liquibase/liquibase-snowflake#118]
**Problem**
Liquibase does not seem to allow for managing change tracking schema separately in multiple Snowflake databases.

**Theory**
Liquibase checks for existing metadata tables across all DBs (which the user has access to), making it difficult to maintain an independent changelog per database.

**Configuration**

- Using Snowflake, with multiple databases.
- Using (or intending to) Liquibase to manage the object definitions in each of them, separately (_this is part of the problem_).
- Using custom meta-data names (but that doesn't appear to be overly significant), via liquibase.properties as follows:
    - databaseChangeLogTableName
    - databaseChangeLogLockTableName
    - liquibaseSchemaName (=PUBLIC)
- Each Snowflake database should have it's own independent set of changesets, tracked in it's own Liquibase meta-data tables.
    - These meta-data values are the same for each database.
- Liquibase is run by a user with SYSADMIN role, which has full access to all of the databases.

**Scenario**
Let's say there are 3 databases: DB1, DB2, and DB3

1. Run liquibase, with the above configuration, providing DB1 in the JDBC URL.
    - It determines that the metadata tables do not yet exist, so they are created.
    - Changesets are applied as expected.
2. Run liquibase, with the above configuration, providing DB2 in the JDBC URL.
    - It does not determine that the metadata tables do not yet exist, so it does not try to create.
    - It then tries to assess the changesets to apply, but runs into an error, because those metadata tables do not actually exist in the specified database.
    - ERROR: Object 'DB2.PUBLIC.DATABASECHANGELOG' does not exist or not authorized.
3. However, if I change the custom table name properties (e.g. to DATABASECHANGELOG2), it then works as expected.
    - To further test my theory, I then run the process with DB3, but it again skips creation and runs into that same error again: Object 'DB3.PUBLIC.DATABASECHANGELOG2' does not exist or not authorized.
    - My assumption is that the "check" for existing metadata tables scans all DBs (which the user has access to), falsely determining that DB2 already has those tables because they exist in DB1.

**Comment by El-Carverino** [comment]
And of course, after a whole day of banging my head against this, leading me to submit this issue, I happened upon a plausible workaround shortly afterwards (via trial & error)...

If you set the liquibaseCatalogName property (or liquibase-catalog-name on CLI), to match the name of the database (e.g. liquibase-catalog-name=DB2), then it works as expected. Even though Snowflake doesn't have a "catalog" layer, it seems that this piece of Liquibase configuration is still relevant. This is something that should probably be better documented. Should I add here in this repo's readme?

**Comment by jvelonis** [comment]
I'm getting the same error even using a different value for --databaseChangeLogTableName for each database.  Scenario:

1. Run `liquibase --databaseChangeLogTableName=DEV_CHANGELOG ... update`.  This works fine.
2. Run `liquibase --databaseChangeLogTableName=PROD_CHANGELOG ... update`.  This also works.
3. Run `liquibase --databaseChangeLogTableName=DEV_CHANGELOG ... update` again, with the same changelog, to test idempotence.  This fails with the following:

```
Liquibase Version: 4.4.3
Liquibase Community 4.4.3 by Datical
[2021-09-21 17:30:18] WARNING [liquibase.database] Unknown database: Snowflake
[2021-09-21 17:30:28] SEVERE [liquibase.integration] SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists. [Failed SQL: (2002) CREATE TABLE LIQUIBASE.DEV_CHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists.
 at liquibase.command.CommandScope.execute(CommandScope.java:153)
 at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
 at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
 at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
 at picocli.CommandLine.access$1300(CommandLine.java:145)
 at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
 at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
 at picocli.CommandLine.execute(CommandLine.java:2078)
 at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:317)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:151)
 at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:289)
 at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:83)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists.
 at liquibase.integration.commandline.Main$1.run(Main.java:447)
 at liquibase.integration.commandline.Main$1.run(Main.java:225)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:151)
 at liquibase.integration.commandline.Main.run(Main.java:225)
 at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
 at liquibase.command.CommandScope.execute(CommandScope.java:147)
 ... 14 more
Caused by: liquibase.exception.DatabaseException: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists. [Failed SQL: (2002) CREATE TABLE LIQUIBASE.DEV_CHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
 at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
 at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
 at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
 at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:134)
 at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:282)
 at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1913)
 at liquibase.Liquibase.lambda$update$1(Liquibase.java:226)
 at liquibase.Scope.lambda$child$0(Scope.java:166)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:165)
 at liquibase.Scope.child(Scope.java:144)
 at liquibase.Liquibase.runInScope(Liquibase.java:2404)
 at liquibase.Liquibase.update(Liquibase.java:211)
 at liquibase.Liquibase.update(Liquibase.java:197)
 at liquibase.integration.commandline.Main.doMigration(Main.java:1882)
 at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:402)
 at liquibase.Scope.lambda$child$0(Scope.java:166)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:165)
 at liquibase.Scope.child(Scope.java:144)
 at liquibase.integration.commandline.Main$1.run(Main.java:401)
 ... 20 more
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists.
 at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
 at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
 at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:442)
 at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:345)
 at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:486)
 at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:197)
 at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:134)
 at net.snowflake.client.core.SFStatement.execute(SFStatement.java:743)
 at net.snowflake.client.core.SFStatement.execute(SFStatement.java:639)
 at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
 at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:337)
 at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
 ... 40 more
Unexpected error running Liquibase: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists. [Failed SQL: (2002) CREATE TABLE LIQUIBASE.DEV_CHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists.
 at liquibase.command.CommandScope.execute(CommandScope.java:153)
 at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
 at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
 at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
 at picocli.CommandLine.access$1300(CommandLine.java:145)
 at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
 at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
 at picocli.CommandLine.execute(CommandLine.java:2078)
 at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:317)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:151)
 at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:289)
 at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:83)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists.
 at liquibase.integration.commandline.Main$1.run(Main.java:447)
 at liquibase.integration.commandline.Main$1.run(Main.java:225)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:151)
 at liquibase.integration.commandline.Main.run(Main.java:225)
 at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
 at liquibase.command.CommandScope.execute(CommandScope.java:147)
 ... 14 more
Caused by: liquibase.exception.DatabaseException: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists. [Failed SQL: (2002) CREATE TABLE LIQUIBASE.DEV_CHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
 at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
 at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
 at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
 at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:134)
 at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:282)
 at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1913)
 at liquibase.Liquibase.lambda$update$1(Liquibase.java:226)
 at liquibase.Scope.lambda$child$0(Scope.java:166)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:165)
 at liquibase.Scope.child(Scope.java:144)
 at liquibase.Liquibase.runInScope(Liquibase.java:2404)
 at liquibase.Liquibase.update(Liquibase.java:211)
 at liquibase.Liquibase.update(Liquibase.java:197)
 at liquibase.integration.commandline.Main.doMigration(Main.java:1882)
 at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:402)
 at liquibase.Scope.lambda$child$0(Scope.java:166)
 at liquibase.Scope.child(Scope.java:175)
 at liquibase.Scope.child(Scope.java:165)
 at liquibase.Scope.child(Scope.java:144)
 at liquibase.integration.commandline.Main$1.run(Main.java:401)
 ... 20 more
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Object 'LIQUIBASE.DEV_CHANGELOG' already exists.
 at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
 at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
 at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:442)
 at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:345)
 at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:486)
 at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:197)
 at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:134)
 at net.snowflake.client.core.SFStatement.execute(SFStatement.java:743)
 at net.snowflake.client.core.SFStatement.execute(SFStatement.java:639)
 at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
 at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:337)
 at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
 ... 40 more
```

I'm running Liquibase in Docker.  The full command line is `['docker', 'run', '--rm', '-v', '/var/tmp://liquibase/changelog', 'liquibase/liquibase', '--log-level=WARN', '--classpath=/liquibase/changelog', '--changeLogFile=liquibase-changelog.json', '--databaseChangeLogTableName=DEV_CHANGELOG', '--driver=net.snowflake.client.jdbc.SnowflakeDriver', '--url=jdbc:snowflake://xxxx.snowflakecomputing.com/?role=SYSADMIN&db=DEV_DB', '--username=XXXX', '--liquibaseSchemaName=LIQUIBASE', '--defaultsFile=/liquibase/changelog/liquibase.docker.properties', 'update']`

The properties file only contains the Snowflake password.

**Comment by FBurguer** [comment]
I couldn't reproduce this issue. I tried making an update for one of the db in our account and then do the same update for another db in the same account. Liquibase made a `DATABASECHANGELOG` and `DATABASECHANGELOGLOCK` on each db. It looks like it got fixed (at least on 4.12)

**Comment by nvoxland** [comment]
I think this is resolved by liquibase/liquibase#3019. There was an issue with newer jdbc drivers with Java 17 that didn't show themselves in other setups.

If you are still having problems after Liquibase 4.13.0 is released, open a new issue in github.com/liquibase/liquibase
